package com.nexus.integration;

import com.nexus.org.OrganizationController;
import io.jsonwebtoken.Jwts;
import io.jsonwebtoken.security.Keys;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.http.MediaType;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.client.RestClient;

import javax.crypto.SecretKey;
import java.nio.charset.StandardCharsets;
import java.time.Instant;
import java.util.*;

@RestController
@RequestMapping("/api/integrations/google")
public class GoogleCalendarController {
    private final JdbcTemplate db; private final OrganizationController orgs; private final String clientId,clientSecret,redirectUri,frontendOrigin,jwtSecret;
    public GoogleCalendarController(JdbcTemplate db,OrganizationController orgs,@Value("${GOOGLE_CLIENT_ID:}") String clientId,@Value("${GOOGLE_CLIENT_SECRET:}") String clientSecret,@Value("${GOOGLE_REDIRECT_URI:}") String redirectUri,@Value("${FRONTEND_ORIGIN:http://localhost:3000}") String frontendOrigin,@Value("${JWT_SECRET:change-me-in-local-development-to-a-long-secret-key}") String jwtSecret){this.db=db;this.orgs=orgs;this.clientId=clientId;this.clientSecret=clientSecret;this.redirectUri=redirectUri;this.frontendOrigin=frontendOrigin;this.jwtSecret=jwtSecret;}
    @GetMapping("/start") public Map<String,String> start(@RequestParam UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);if(clientId.isBlank()||redirectUri.isBlank())throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.SERVICE_UNAVAILABLE,"Google Calendar is not configured.");String state=Jwts.builder().claim("orgId",orgId.toString()).claim("userId",a.getName()).expiration(Date.from(Instant.now().plusSeconds(600))).signWith(key()).compact();String url="https://accounts.google.com/o/oauth2/v2/auth?client_id="+enc(clientId)+"&redirect_uri="+enc(redirectUri)+"&response_type=code&access_type=offline&prompt=consent&scope="+enc("https://www.googleapis.com/auth/calendar.events")+"&state="+enc(state);return Map.of("url",url);}
    @GetMapping("/callback") public org.springframework.http.ResponseEntity<Void> callback(@RequestParam String code,@RequestParam String state){var claims=Jwts.parser().verifyWith(key()).build().parseSignedClaims(state).getPayload();UUID orgId=UUID.fromString(claims.get("orgId",String.class));Map<?,?> token=RestClient.create().post().uri("https://oauth2.googleapis.com/token").contentType(MediaType.APPLICATION_FORM_URLENCODED).body("code="+enc(code)+"&client_id="+enc(clientId)+"&client_secret="+enc(clientSecret)+"&redirect_uri="+enc(redirectUri)+"&grant_type=authorization_code").retrieve().body(Map.class);if(token==null||token.get("access_token")==null)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.BAD_GATEWAY,"Google token exchange failed.");String access=String.valueOf(token.get("access_token"));String refresh=token.get("refresh_token")==null?null:String.valueOf(token.get("refresh_token"));Number expires=token.get("expires_in") instanceof Number n?n:3600;db.update("INSERT INTO integration.google_connections(id,organization_id,access_token,refresh_token,expires_at) VALUES(?,?,?,?,now()+(? * interval '1 second')) ON CONFLICT(organization_id) DO UPDATE SET access_token=EXCLUDED.access_token,refresh_token=COALESCE(EXCLUDED.refresh_token,integration.google_connections.refresh_token),expires_at=EXCLUDED.expires_at,updated_at=now()",UUID.randomUUID(),orgId,access,refresh,expires.longValue());return org.springframework.http.ResponseEntity.status(302).header("Location",frontendOrigin+"/calendar?google=connected").build();}
    @GetMapping("/status") public Map<String,Boolean> status(@RequestParam UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);return Map.of("connected",db.queryForObject("SELECT count(*) FROM integration.google_connections WHERE organization_id=?",Integer.class,orgId)>0);}
    @PostMapping("/sync") public Map<String,Object> sync(@RequestParam UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);Map<String,Object> connection=db.queryForMap("SELECT access_token,refresh_token,expires_at,sync_token FROM integration.google_connections WHERE organization_id=?",orgId);String access=validAccess(orgId,connection);int pushed=0,pulled=0;for(Map<String,Object> event:db.queryForList("SELECT id,title,description,starts_at,ends_at,location,recurrence_rule FROM calendar.events WHERE organization_id=? AND deleted_at IS NULL AND google_event_id IS NULL",orgId)){Map<String,Object> body=new LinkedHashMap<>();body.put("summary",event.get("title"));body.put("description",event.get("description"));body.put("location",event.get("location"));body.put("start",Map.of("dateTime",event.get("starts_at").toString()));body.put("end",Map.of("dateTime",event.get("ends_at").toString()));if(event.get("recurrence_rule")!=null)body.put("recurrence",List.of(event.get("recurrence_rule")));Map<?,?> created=RestClient.create().post().uri("https://www.googleapis.com/calendar/v3/calendars/primary/events").header("Authorization","Bearer "+access).contentType(MediaType.APPLICATION_JSON).body(body).retrieve().body(Map.class);if(created!=null&&created.get("id")!=null){db.update("UPDATE calendar.events SET google_event_id=?,sync_status='SYNCED' WHERE id=?",created.get("id"),event.get("id"));pushed++;}}
        String syncToken=Objects.toString(connection.get("sync_token"),"");String url="https://www.googleapis.com/calendar/v3/calendars/primary/events?singleEvents=false&showDeleted=true"+(syncToken.isBlank()?"":"&syncToken="+enc(syncToken));Map<?,?> result=RestClient.create().get().uri(url).header("Authorization","Bearer "+access).retrieve().body(Map.class);if(result!=null&&result.get("items") instanceof List<?> items){for(Object raw:items){if(!(raw instanceof Map<?,?> item)||item.get("id")==null||"cancelled".equals(item.get("status")))continue;Map<?,?> start=item.get("start") instanceof Map<?,?> m?m:Map.of(),end=item.get("end") instanceof Map<?,?> m?m:Map.of();Object starts=start.get("dateTime"),ends=end.get("dateTime");if(starts==null||ends==null)continue;UUID id=UUID.randomUUID();int changed=db.update("UPDATE calendar.events SET title=?,description=?,starts_at=?::timestamptz,ends_at=?::timestamptz,location=?,sync_status='SYNCED' WHERE organization_id=? AND google_event_id=?",Objects.toString(item.get("summary"),"Google event"),Objects.toString(item.get("description"),""),starts,ends,item.get("location"),orgId,item.get("id"));if(changed==0){db.update("INSERT INTO calendar.events(id,organization_id,title,description,starts_at,ends_at,kind,created_by,google_event_id,sync_status) VALUES(?,?,?,?,?::timestamptz,?::timestamptz,'GOOGLE',? ,?,'SYNCED')",id,orgId,Objects.toString(item.get("summary"),"Google event"),Objects.toString(item.get("description"),""),starts,ends,UUID.fromString(a.getName()),item.get("id"));}pulled++;}}if(result!=null&&result.get("nextSyncToken")!=null)db.update("UPDATE integration.google_connections SET sync_token=?,last_synced_at=now(),updated_at=now() WHERE organization_id=?",result.get("nextSyncToken"),orgId);return Map.of("pushed",pushed,"pulled",pulled);}
    private String validAccess(UUID orgId,Map<String,Object> connection){Object expiry=connection.get("expires_at");if(expiry instanceof java.time.OffsetDateTime t&&t.isAfter(java.time.OffsetDateTime.now().plusMinutes(1)))return String.valueOf(connection.get("access_token"));String refresh=Objects.toString(connection.get("refresh_token"),"");if(refresh.isBlank())return String.valueOf(connection.get("access_token"));Map<?,?> token=RestClient.create().post().uri("https://oauth2.googleapis.com/token").contentType(MediaType.APPLICATION_FORM_URLENCODED).body("client_id="+enc(clientId)+"&client_secret="+enc(clientSecret)+"&refresh_token="+enc(refresh)+"&grant_type=refresh_token").retrieve().body(Map.class);if(token==null||token.get("access_token")==null)throw new org.springframework.web.server.ResponseStatusException(org.springframework.http.HttpStatus.BAD_GATEWAY,"Google token refresh failed.");String access=String.valueOf(token.get("access_token"));Number seconds=token.get("expires_in") instanceof Number n?n:3600;db.update("UPDATE integration.google_connections SET access_token=?,expires_at=now()+(? * interval '1 second'),updated_at=now() WHERE organization_id=?",access,seconds.longValue(),orgId);return access;}
    private void member(UUID id,org.springframework.security.core.Authentication a){orgs.requireMember(id,UUID.fromString(a.getName()));}
    private SecretKey key(){return Keys.hmacShaKeyFor(jwtSecret.getBytes(StandardCharsets.UTF_8));}
    private static String enc(String s){return java.net.URLEncoder.encode(s,StandardCharsets.UTF_8);}
}
