'use client'

import AppShell from '../../components/AppShell'
import { Search, Save, UserPlus, Users, X } from '../../components/icons'
import { useEffect, useState } from 'react'
import { api } from '../../lib/api'
import { useWorkspace, workspaceIds } from '../../lib/workspace'

type Member = { id: string; name: string; email: string; role: string; title?: string; department?: string; bio?: string; location?: string; availability?: string; skills?: string[] }
type Invite = { id: string; email: string; status: string }
type Profile = { title: string; department: string; bio: string; location: string; availability: string; skills: string }
const emptyProfile: Profile = { title: '', department: '', bio: '', location: '', availability: 'AVAILABLE', skills: '' }

export default function DirectoryPage() {
  const { workspace } = useWorkspace(); const { orgId } = workspaceIds(workspace)
  const [members, setMembers] = useState<Member[]>([]); const [invites, setInvites] = useState<Invite[]>([]); const [query, setQuery] = useState(''); const [showInvite, setShowInvite] = useState(false); const [email, setEmail] = useState(''); const [editing, setEditing] = useState<Member | null>(null); const [pendingRemoval, setPendingRemoval] = useState<Member | null>(null); const [profile, setProfile] = useState<Profile>(emptyProfile); const [saving, setSaving] = useState(false); const [actionError, setActionError] = useState(''); const [notice, setNotice] = useState('')
  const load = async () => { if (!orgId) return; const [people, pending] = await Promise.all([api<Member[]>(`/orgs/${orgId}/directory`), api<Invite[]>(`/orgs/${orgId}/invitations`)]); setMembers(people); setInvites(pending) }
  useEffect(() => { void load().catch(err => setActionError(err instanceof Error ? err.message : 'Directory could not be loaded.')) }, [orgId])
  const invite = async () => { if (!email.trim() || !orgId) return; setActionError(''); try { const item = await api<Invite>(`/orgs/${orgId}/invitations`, { method: 'POST', body: JSON.stringify({ email: email.trim(), role: 'MEMBER' }) }); setInvites(x => [item, ...x]); setEmail(''); setShowInvite(false); setNotice('Invitation recorded.') } catch (err) { setActionError(err instanceof Error ? err.message : 'Invitation could not be sent.') } }
  const changeRole = async (member: Member, role: string) => { if (!orgId) return; try { await api(`/orgs/${orgId}/members/${member.id}/role`, { method: 'PATCH', body: JSON.stringify({ role }) }); setMembers(x => x.map(v => v.id === member.id ? { ...v, role } : v)); setNotice('Role updated.') } catch (err) { setActionError(err instanceof Error ? err.message : 'Role could not be changed.') } }
  const openProfile = (member: Member) => { setEditing(member); setProfile({ title: member.title || '', department: member.department || '', bio: member.bio || '', location: member.location || '', availability: member.availability || 'AVAILABLE', skills: Array.isArray(member.skills) ? member.skills.join(', ') : '' }) }
  const saveProfile = async () => { if (!editing || !orgId) return; setSaving(true); setActionError(''); try { const updated = await api<Member>(`/orgs/${orgId}/directory/${editing.id}`, { method: 'PUT', body: JSON.stringify({ ...profile, skills: profile.skills.split(',').map(item => item.trim()).filter(Boolean) }) }); setMembers(x => x.map(item => item.id === editing.id ? updated : item)); setEditing(null); setNotice('Profile updated.') } catch (err) { setActionError(err instanceof Error ? err.message : 'Profile could not be updated.') } finally { setSaving(false) } }
  const remove = async () => { if (!orgId || !pendingRemoval) return; setSaving(true); setActionError(''); try { await api(`/orgs/${orgId}/members/${pendingRemoval.id}`, { method: 'DELETE' }); setMembers(x => x.filter(v => v.id !== pendingRemoval.id)); setNotice(`${pendingRemoval.name} removed from the workspace.`); setPendingRemoval(null) } catch (err) { setActionError(err instanceof Error ? err.message : 'Member could not be removed.') } finally { setSaving(false) } }
  const visible = members.filter(m => (m.name + ' ' + m.email + ' ' + (m.department || '') + ' ' + (m.title || '')).toLowerCase().includes(query.toLowerCase()))

  return <AppShell><div className="page"><div className="page-heading"><div><div className="eyebrow">PEOPLE</div><h1>Directory</h1><p className="muted">Organization members, roles, profiles, and invitations.</p></div><button className="button primary" onClick={() => setShowInvite(true)}><UserPlus size={15}/> Invite member</button></div>{actionError && <div className="form-error"><span>{actionError}</span><button className="icon-button" aria-label="Dismiss error" onClick={() => setActionError('')}><X size={15}/></button></div>}{notice && <div className="form-success"><span>{notice}</span><button className="icon-button" aria-label="Dismiss message" onClick={() => setNotice('')}><X size={15}/></button></div>}<div className="card"><div className="search" style={{ maxWidth: 420, background: 'var(--surface)' }}><Search size={15}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="Search people, teams, titles" aria-label="Search people" /></div></div><div className="card" style={{ marginTop: 16 }}>{visible.length === 0 ? <div className="empty"><Users size={32}/><p>No members found.</p></div> : visible.map(member => <div className="task-row" key={member.id}><span className="avatar">{member.name.slice(0, 1).toUpperCase()}</span><div className="task-copy"><strong>{member.name}</strong><small>{member.title || member.department || member.email}{member.location ? ` · ${member.location}` : ''} · {member.availability || 'AVAILABLE'}</small></div><select aria-label={`Role for ${member.name}`} value={member.role} onChange={e => void changeRole(member, e.target.value)}><option value="OWNER">Owner</option><option value="ADMIN">Admin</option><option value="MEMBER">Member</option></select><div className="actions"><button className="button" onClick={() => openProfile(member)}>Profile</button><button className="button" onClick={() => setPendingRemoval(member)}>Remove</button></div></div>)}</div>{invites.length > 0 && <div className="card" style={{ marginTop: 16 }}><h2>Pending invitations</h2>{invites.map(item => <div className="task-row" key={item.id}><UserPlus size={16}/><div className="task-copy"><strong>{item.email}</strong><small>{item.status}</small></div></div>)}</div>}
    {showInvite && <div className="modal-backdrop" onClick={() => setShowInvite(false)}><div className="card modal-card" onClick={event => event.stopPropagation()}><div className="card-header"><h2>Invite member</h2><button className="icon-button" aria-label="Close invite" onClick={() => setShowInvite(false)}><X size={16}/></button></div><div className="field"><label htmlFor="invite-email">Work email</label><input id="invite-email" autoFocus type="email" value={email} onChange={e => setEmail(e.target.value)} /></div><button className="button primary" onClick={() => void invite()}>Send invitation</button></div></div>}
    {editing && <div className="modal-backdrop" onClick={() => setEditing(null)}><div className="card modal-card" onClick={event => event.stopPropagation()}><div className="card-header"><div><div className="eyebrow">EMPLOYEE PROFILE</div><h2>{editing.name}</h2></div><button className="icon-button" aria-label="Close profile" onClick={() => setEditing(null)}><X size={16}/></button></div><p className="muted">Update the profile visible to authorized workspace members.</p><div className="forms-inline-fields"><div className="field"><label htmlFor="profile-title">Title</label><input id="profile-title" value={profile.title} onChange={e => setProfile({ ...profile, title: e.target.value })}/></div><div className="field"><label htmlFor="profile-department">Department</label><input id="profile-department" value={profile.department} onChange={e => setProfile({ ...profile, department: e.target.value })}/></div></div><div className="forms-inline-fields"><div className="field"><label htmlFor="profile-location">Location</label><input id="profile-location" value={profile.location} onChange={e => setProfile({ ...profile, location: e.target.value })}/></div><div className="field"><label htmlFor="profile-availability">Availability</label><select id="profile-availability" value={profile.availability} onChange={e => setProfile({ ...profile, availability: e.target.value })}><option value="AVAILABLE">Available</option><option value="BUSY">Busy</option><option value="OOO">Out of office</option></select></div></div><div className="field"><label htmlFor="profile-skills">Skills</label><input id="profile-skills" value={profile.skills} onChange={e => setProfile({ ...profile, skills: e.target.value })} placeholder="Design, Operations, Finance"/></div><div className="field"><label htmlFor="profile-bio">Bio</label><textarea id="profile-bio" value={profile.bio} onChange={e => setProfile({ ...profile, bio: e.target.value })}/></div><button className="button primary" disabled={saving} onClick={() => void saveProfile()}><Save size={15}/>{saving ? 'Saving…' : 'Save profile'}</button></div></div>}
    {pendingRemoval && <div className="modal-backdrop" onClick={() => setPendingRemoval(null)}><div className="card modal-card confirmation-card" role="alertdialog" aria-modal="true" onClick={event => event.stopPropagation()}><div className="eyebrow">DIRECTORY / REMOVE</div><h2>Remove {pendingRemoval.name}?</h2><p className="muted">This revokes their membership in the current Nexus organization. Their user account is not deleted.</p><div className="actions"><button className="button" onClick={() => setPendingRemoval(null)}>Cancel</button><button className="button danger" disabled={saving} onClick={() => void remove()}>{saving ? 'Removing…' : 'Remove member'}</button></div></div></div>}
  </div></AppShell>
}
