'use client'
import AppShell from '../../components/AppShell'; import { useEffect, useState } from 'react'; import { FileText, FolderOpen, Plus, Save, Clock } from '../../components/icons'; import {api} from '../../lib/api'; import {useWorkspace,workspaceIds} from '../../lib/workspace'
type Doc = { id:string; title: string; content: string; version: number }
export default function Documents() { const [docs, setDocs] = useState<Doc[]>([]); const [active, setActive] = useState<Doc | null>(null); const [saved, setSaved] = useState(true)
  const {workspace}=useWorkspace(); const {orgId,teamId}=workspaceIds(workspace)
  useEffect(() => { if(orgId)void api<Doc[]>(`/orgs/${orgId}/documents`).then(setDocs).catch(()=>{}); if (new URLSearchParams(window.location.search).get('new') === '1') void create() }, [orgId])
  const create = async () => { if(!orgId)return; const doc = await api<Doc>(`/orgs/${orgId}/documents`,{method:'POST',body:JSON.stringify({title:'Untitled document',content:'',teamId})}); setDocs(current => [doc, ...current]); setActive(doc); setSaved(false) }
  const update = (next: Doc) => { setActive(next); setDocs(current => current.map(doc => doc.id === next.id ? next : doc)); setSaved(false) }
  const save = async()=>{if(!active)return;const next=await api<Doc>(`/documents/${active.id}`,{method:'PUT',body:JSON.stringify({title:active.title,content:active.content})});setActive(next);setDocs(x=>x.map(d=>d.id===next.id?next:d));setSaved(true)}
  return <AppShell><div className="page"><div className="page-heading"><div><div className="eyebrow">KNOWLEDGE BASE</div><h1>Documents</h1><p className="muted">Create and maintain your team’s shared context.</p></div><button className="button primary" onClick={()=>void create()}><Plus size={15}/> New document</button></div><div className="doc-editor"><aside className="card"><div className="card-header"><h2>Documents</h2><FolderOpen size={16} className="muted"/></div>{docs.length === 0 ? <div className="empty">No documents yet.</div> : docs.map(doc=><button key={doc.id} type="button" onClick={()=>{setActive(doc);setSaved(true)}} className={`nav-item ${active?.id===doc.id?'active':''}`} style={{width:'100%',textAlign:'left'}}><FileText size={15}/><span>{doc.title || 'Untitled document'}</span></button>)}</aside>{active ? <section className="card editor"><div className="card-header"><div><input value={active.title} onChange={e=>update({...active,title:e.target.value})} aria-label="Document title" style={{fontSize:20,fontWeight:600,border:0,outline:0,background:'transparent',color:'var(--text)',width:'100%'}}/><div className="muted" style={{fontSize:12,marginTop:6}}>{saved?'Saved to workspace':'Unsaved changes'} · Version {active.version}</div></div><div className="actions"><button className="button" type="button"><Clock size={15}/> History</button><button className="button primary" onClick={()=>void save()}><Save size={15}/> Save</button></div></div><textarea value={active.content} onChange={e=>update({...active,content:e.target.value})} aria-label="Document content" /></section> : <section className="card empty"><FileText size={32}/><p>Select a document or create one.</p><button className="button primary" onClick={()=>void create()}><Plus size={15}/> New document</button></section>}</div></div></AppShell> }
