'use client'
import { useState } from 'react'
import { CheckCircle2, ChevronRight, Users } from '../../components/icons'

const steps = ['Your workspace', 'Invite your team', 'Make it yours']
export default function OnboardingPage() {
  const [step, setStep] = useState(0)
  return <div className="auth-page"><div className="auth-card" style={{ width: 'min(620px,100%)' }}><div className="brand"><div className="brand-mark">N</div><span>Nexus</span></div><div className="onboarding-steps">{steps.map((label, i) => <div className={`onboarding-step ${i <= step ? 'done' : ''}`} key={label}><span>{i < step ? <CheckCircle2 size={14}/> : i + 1}</span>{label}</div>)}</div>{step === 0 && <><h1>Set up your workspace</h1><p>Give your team a home they’ll recognize.</p><div className="field"><label htmlFor="workspace-name">Workspace name</label><input id="workspace-name" defaultValue="Nexus Engineering" /></div><div className="field"><label htmlFor="workspace-purpose">What are you working on?</label><select id="workspace-purpose"><option>Product development</option><option>Marketing</option><option>Operations</option><option>Community</option></select></div></>}{step === 1 && <><h1>Invite your team</h1><p>Start with the people you collaborate with most. You can always invite more later.</p><div className="invite-row"><Users size={18} color="var(--brand)"/><input placeholder="teammate@company.com"/><button className="button">Add</button></div><div className="empty" style={{ paddingBottom: 5 }}>You can skip this for now.</div></>}{step === 2 && <><h1>Make Nexus yours</h1><p>Choose the defaults that help your team feel at home.</p><div className="theme-choice"><div><strong>Use system theme</strong><small>Automatically match your device.</small></div><CheckCircle2 size={18} color="var(--brand)"/></div><div className="theme-choice"><div><strong>Start with Engineering</strong><small>Includes a team, #general, and starter docs.</small></div><CheckCircle2 size={18} color="var(--brand)"/></div></>}<button className="button primary" style={{ width: '100%', justifyContent: 'center', marginTop: 20 }} onClick={() => step < 2 ? setStep(step + 1) : window.location.href = '/'}>{step < 2 ? 'Continue' : 'Open workspace'} <ChevronRight size={15}/></button>{step > 0 && <button className="button" style={{ width: '100%', justifyContent: 'center', marginTop: 8 }} onClick={() => setStep(step - 1)}>Back</button>}</div></div>
}
