'use client'
import AppShell from '../../components/AppShell'
import { FolderKanban, Plus, X } from '../../components/icons'
import { useEffect, useMemo, useState } from 'react'
import { api } from '../../lib/api'
import { useWorkspace, workspaceIds } from '../../lib/workspace'
type Project={id:string;name:string;description:string;status:string;starts_on?:string;ends_on?:string;budget:number;health:string;task_count:number;completed_count:number;critical_risks:number}
type Gantt={tasks:Array<{id:string;title:string;status:string;due_date?:string}>;milestones:Array<{id:string;name:string;due_date?:string;status:string}>}
type Risk={id:string;title:string;probability:number;impact:number;score:number;status:string;mitigation?:string}
type Template={id:string;name:string;description:string;tasks:unknown[]}
export default function Projects(){
 const{workspace}=useWorkspace();const{orgId,teamId}=workspaceIds(workspace);const[items,setItems]=useState<Project[]>([]);const[selected,setSelected]=useState<Project|null>(null);const[gantt,setGantt]=useState<Gantt|null>(null);const[risks,setRisks]=useState<Risk[]>([]);const[templates,setTemplates]=useState<Template[]>([]);const[show,setShow]=useState(false);const[error,setError]=useState('');const[name,setName]=useState('');const[description,setDescription]=useState('');const[start,setStart]=useState('');const[end,setEnd]=useState('');const[budget,setBudget]=useState('');const[milestone,setMilestone]=useState('');const[risk,setRisk]=useState('');const[saving,setSaving]=useState(false)
 useEffect(()=>{if(orgId)void Promise.all([api<Project[]>(`/orgs/${orgId}/projects`),api<Template[]>(`/orgs/${orgId}/project-templates`)]).then(([projects,presets])=>{setItems(projects);setTemplates(presets)}).catch(reason=>setError(reason instanceof Error?reason.message:'Projects could not be loaded.'))},[orgId])
 const open=async(project:Project)=>{setSelected(project);try{const[timeline,register]=await Promise.all([api<Gantt>(`/projects/${project.id}/gantt`),api<Risk[]>(`/projects/${project.id}/risks`)]);setGantt(timeline);setRisks(register)}catch(reason){setError(reason instanceof Error?reason.message:'Project plan could not be loaded.')}}
 const create=async()=>{if(!name.trim()||!orgId)return;setSaving(true);try{const item=await api<Project>(`/orgs/${orgId}/projects`,{method:'POST',body:JSON.stringify({name:name.trim(),description:description.trim(),teamId,startsOn:start||null,endsOn:end||null,budget:Number(budget)||0,status:'PLANNING',health:'GREEN'})});setItems(current=>[item,...current]);setShow(false);setName('');setDescription('');setStart('');setEnd('');setBudget('')}catch(reason){setError(reason instanceof Error?reason.message:'Project could not be created.')}finally{setSaving(false)}}
 const addMilestone=async()=>{if(!selected||!milestone.trim())return;const item=await api<Gantt['milestones'][number]>(`/projects/${selected.id}/milestones`,{method:'POST',body:JSON.stringify({name:milestone,dueDate:end||null,status:'OPEN'})});setGantt(current=>current?{...current,milestones:[...current.milestones,item]}:current);setMilestone('')}
 const addRisk=async()=>{if(!selected||!risk.trim())return;const item=await api<Risk>(`/projects/${selected.id}/risks`,{method:'POST',body:JSON.stringify({title:risk,probability:3,impact:3,status:'OPEN'})});setRisks(current=>[item,...current]);setRisk('')};const progress=(project:Project)=>project.task_count?Math.round(project.completed_count/project.task_count*100):0;const health=useMemo(()=>selected?(selected.critical_risks>0?'RED':selected.health):'GREEN',[selected])
 return <AppShell><div className="page"><div className="page-heading"><div><div className="eyebrow">PORTFOLIO / DELIVERY</div><h1>Projects</h1><p className="muted">Plan timelines, milestones, budgets, risks, and delivery health.</p></div><button className="button primary" onClick={()=>setShow(true)}><Plus size={15}/> New project</button></div>{error&&<div className="form-error">{error}</div>}<div className="metric-grid">{items.map(project=><button className="card project-summary" key={project.id} onClick={()=>void open(project)}><div className="card-header"><h2>{project.name}</h2><span className={`health-dot ${project.health?.toLowerCase()}`}>{project.health}</span></div><p className="muted">{project.description||'No description'}</p><div className="project-progress"><i style={{width:`${progress(project)}%`}}/></div><small>{progress(project)}% complete · {project.task_count||0} tasks · Budget {Number(project.budget||0).toLocaleString()}</small></button>)}</div>{items.length===0&&<div className="card empty"><FolderKanban size={32}/><p>No projects yet.</p><button className="button primary" onClick={()=>setShow(true)}>Create project</button></div>}
 {selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><div className="card modal-card suite-detail" onClick={event=>event.stopPropagation()}><div className="card-header"><div><div className="eyebrow">PROJECT HEALTH / {health}</div><h2>{selected.name}</h2></div><button className="icon-button" onClick={()=>setSelected(null)}><X size={16}/></button></div><div className="suite-columns"><section><h3>Gantt timeline</h3>{gantt?.tasks.map(task=><div className="gantt-row" key={task.id}><span>{task.title}</span><i style={{width:task.status==='DONE'?'100%':'55%'}}/><small>{task.due_date||'No deadline'}</small></div>)}{!gantt?.tasks.length&&<p className="muted">Add tasks to build the timeline.</p>}<h3>Milestones</h3>{gantt?.milestones.map(item=><div className="task-row" key={item.id}><strong>{item.name}</strong><small>{item.due_date||'No due date'} · {item.status}</small></div>)}<div className="inline-form"><input value={milestone} onChange={e=>setMilestone(e.target.value)} placeholder="New milestone"/><button className="button" onClick={()=>void addMilestone()}>Add</button></div></section><section><h3>Risk register</h3>{risks.map(item=><div className="task-row" key={item.id}><div className="task-copy"><strong>{item.title}</strong><small>Score {item.score} · {item.status}</small></div></div>)}<div className="inline-form"><input value={risk} onChange={e=>setRisk(e.target.value)} placeholder="New delivery risk"/><button className="button" onClick={()=>void addRisk()}>Add</button></div><h3>Templates</h3><p className="muted">{templates.length?templates.map(item=>item.name).join(', '):'No templates saved yet.'}</p></section></div></div></div>}
 {show&&<div className="modal-backdrop"><div className="card modal-card"><div className="card-header"><h2>New project</h2><button className="icon-button" onClick={()=>setShow(false)}>×</button></div><div className="field"><label>Name</label><input autoFocus value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Description</label><textarea value={description} onChange={e=>setDescription(e.target.value)}/></div><div className="forms-inline-fields"><div className="field"><label>Start</label><input type="date" value={start} onChange={e=>setStart(e.target.value)}/></div><div className="field"><label>Target end</label><input type="date" value={end} onChange={e=>setEnd(e.target.value)}/></div></div><div className="field"><label>Budget</label><input type="number" min="0" value={budget} onChange={e=>setBudget(e.target.value)}/></div><button className="button primary" disabled={saving} onClick={()=>void create()}>{saving?'Creating…':'Create project'}</button></div></div>}</div></AppShell>
}
