'use client'
import AppShell from '../../components/AppShell'
import { CalendarDays, Copy, Mic, Plus, Video } from '../../components/icons'
import { useState } from 'react'

export default function MeetingsPage() { const [room, setRoom] = useState(false); const [mic, setMic] = useState(true); return <AppShell><div className="page">
  <div className="page-heading"><div><div className="eyebrow">COLLABORATION</div><h1>Meetings</h1><p className="muted">Schedule focused conversations and keep the outcomes close to the work.</p></div><div className="actions"><button className="button" onClick={() => setRoom(true)}><Video size={15}/> Start instant meeting</button><button className="button primary"><Plus size={15}/> Schedule meeting</button></div></div>
  <div className="grid dashboard-grid"><section className="card"><div className="card-header"><h2>Next up</h2><span className="badge">Today</span></div><div className="meeting-hero"><Video size={24} color="var(--brand)"/><div><h2>Sprint standup</h2><p className="muted">10:00 AM · 30 minutes · Engineering</p><div className="actions" style={{ marginTop: 15 }}><button className="button primary" onClick={() => setRoom(true)}>Join meeting</button><button className="button"><CalendarDays size={15}/> Add to calendar</button></div></div></div></section><section className="card"><div className="card-header"><h2>Quick room</h2><Video size={17} className="muted"/></div><p className="muted" style={{ fontSize: 13 }}>Start a room and invite your team with one link.</p><div className="room-link"><code>meet.nexus.local/room/platform</code><button className="icon-button" aria-label="Copy meeting link"><Copy size={15}/></button></div><button className="button" onClick={() => setRoom(true)}>Open room</button></section></div>
  <section className="card" style={{ marginTop: 16 }}><div className="card-header"><h2>Upcoming meetings</h2><button className="button">View calendar</button></div>{[['Product planning','Friday, Aug 8 · 11:30 AM','Product'],['Design review','Wednesday, Aug 6 · 2:00 PM','Design'],['1:1 with Priya','Monday, Aug 10 · 4:00 PM','People']].map(([title,meta,team]) => <div className="task-row" key={title}><span className="avatar" style={{ background: '#6366f1' }}><Video size={14}/></span><div className="task-copy"><strong>{title}</strong><small>{meta} · {team}</small></div><button className="button">Details</button></div>)}</section>
  {room && <div className="meeting-room"><div className="meeting-stage"><div className="meeting-brand"><span className="brand-mark">N</span> Nexus room</div><div className="meeting-empty"><Video size={42}/><h2>You’re the only one here</h2><p>Share the room link to invite your team.</p><div className="room-link"><code>meet.nexus.local/room/platform</code><Copy size={15}/></div></div><div className="meeting-controls"><button className={`button ${mic ? 'primary' : ''}`} onClick={() => setMic(!mic)}><Mic size={16}/> {mic ? 'Mute' : 'Unmute'}</button><button className="button primary"><Video size={16}/> Camera</button><button className="button">Share screen</button><button className="button" onClick={() => setRoom(false)}>Leave</button></div></div></div>}
 </div></AppShell> }
