package com.nexus.document;

import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import java.util.*;

@RestController @RequestMapping("/api")
public class DocumentController {
 private final JdbcTemplate db; public DocumentController(JdbcTemplate db){this.db=db;}
 record CreateDoc(@NotBlank String title,String content,UUID teamId){} record UpdateDoc(@NotBlank String title,String content){}
 @GetMapping("/orgs/{orgId}/documents") public List<Map<String,Object>> list(@PathVariable UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);return db.queryForList("SELECT id,title,content,version,team_id,updated_at FROM document.documents WHERE organization_id=? AND deleted_at IS NULL ORDER BY updated_at DESC",orgId);}
 @PostMapping("/orgs/{orgId}/documents") public Map<String,Object> create(@PathVariable UUID orgId,@Valid @RequestBody CreateDoc r,org.springframework.security.core.Authentication a){UUID uid=UUID.fromString(a.getName());member(orgId,a);UUID id=UUID.randomUUID();db.update("INSERT INTO document.documents(id,organization_id,team_id,title,content,created_by) VALUES(?,?,?,?,?,?)",id,orgId,r.teamId(),r.title(),Objects.toString(r.content(),""),uid);db.update("INSERT INTO document.document_versions(id,document_id,version,title,content,created_by) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),id,1,r.title(),Objects.toString(r.content(),""),uid);return db.queryForMap("SELECT id,title,content,version,team_id,updated_at FROM document.documents WHERE id=?",id);}
 @GetMapping("/documents/{id}") public Map<String,Object> get(@PathVariable UUID id,org.springframework.security.core.Authentication a){Map<String,Object>d=db.queryForMap("SELECT * FROM document.documents WHERE id=? AND deleted_at IS NULL",id);member((UUID)d.get("organization_id"),a);return d;}
 @PutMapping("/documents/{id}") public Map<String,Object> update(@PathVariable UUID id,@Valid @RequestBody UpdateDoc r,org.springframework.security.core.Authentication a){UUID uid=UUID.fromString(a.getName());Map<String,Object>d=get(id,a);int v=((Number)d.get("version")).intValue()+1;db.update("UPDATE document.documents SET title=?,content=?,version=?,updated_at=now() WHERE id=?",r.title(),Objects.toString(r.content(),""),v,id);db.update("INSERT INTO document.document_versions(id,document_id,version,title,content,created_by) VALUES(?,?,?,?,?,?)",UUID.randomUUID(),id,v,r.title(),Objects.toString(r.content(),""),uid);return get(id,a);}
 @GetMapping("/documents/{id}/versions") public List<Map<String,Object>> versions(@PathVariable UUID id,org.springframework.security.core.Authentication a){get(id,a);return db.queryForList("SELECT id,version,title,created_by,created_at FROM document.document_versions WHERE document_id=? ORDER BY version DESC",id);}
 private void member(UUID org,org.springframework.security.core.Authentication a){if(db.queryForObject("SELECT count(*) FROM org.memberships WHERE organization_id=? AND user_id=?",Integer.class,org,UUID.fromString(a.getName()))==0)throw new SecurityException("You do not have access to this workspace.");}
}
