package com.nexus.work;

import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import java.sql.Date; import java.time.LocalDate; import java.util.*;

@RestController @RequestMapping("/api")
public class WorkController {
 private final JdbcTemplate db; public WorkController(JdbcTemplate db){this.db=db;}
 record CreateProject(@NotBlank String name,String description,UUID teamId){} record CreateTask(@NotBlank String title,String description,UUID teamId,UUID projectId,String priority,UUID assigneeId,LocalDate dueDate){} record UpdateTask(String title,String description,String status,String priority,UUID assigneeId,LocalDate dueDate){}
 @GetMapping("/orgs/{orgId}/projects") public List<Map<String,Object>> projects(@PathVariable UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);return db.queryForList("SELECT id,name,description,team_id FROM project.projects WHERE organization_id=? AND deleted_at IS NULL ORDER BY updated_at DESC",orgId);}
 @PostMapping("/orgs/{orgId}/projects") public Map<String,Object> project(@PathVariable UUID orgId,@Valid @RequestBody CreateProject r,org.springframework.security.core.Authentication a){member(orgId,a);UUID id=UUID.randomUUID();db.update("INSERT INTO project.projects(id,organization_id,team_id,name,description) VALUES(?,?,?,?,?)",id,orgId,r.teamId(),r.name(),r.description());return Map.of("id",id,"name",r.name(),"description",Objects.toString(r.description(),""),"teamId",r.teamId());}
 @GetMapping("/orgs/{orgId}/tasks") public List<Map<String,Object>> tasks(@PathVariable UUID orgId, @RequestParam(required=false) UUID teamId,org.springframework.security.core.Authentication a){member(orgId,a);String q="SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE organization_id=? AND deleted_at IS NULL";return teamId==null?db.queryForList(q+" ORDER BY due_date NULLS LAST,updated_at DESC",orgId):db.queryForList(q+" AND team_id=? ORDER BY due_date NULLS LAST,updated_at DESC",orgId,teamId);}
 @PostMapping("/orgs/{orgId}/tasks") public Map<String,Object> task(@PathVariable UUID orgId,@Valid @RequestBody CreateTask r,org.springframework.security.core.Authentication a){member(orgId,a);UUID id=UUID.randomUUID();db.update("INSERT INTO project.tasks(id,organization_id,project_id,team_id,title,description,priority,assignee_id,due_date) VALUES(?,?,?,?,?,?,?,?,?)",id,orgId,r.projectId(),r.teamId(),r.title(),r.description(),Objects.toString(r.priority(),"MEDIUM"),r.assigneeId(),r.dueDate()==null?null:Date.valueOf(r.dueDate()));return db.queryForMap("SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE id=?",id);}
 @PatchMapping("/tasks/{id}") public Map<String,Object> update(@PathVariable UUID id,@RequestBody UpdateTask r,org.springframework.security.core.Authentication a){UUID uid=UUID.fromString(a.getName());Map<String,Object> row=db.queryForMap("SELECT organization_id FROM project.tasks WHERE id=? AND deleted_at IS NULL",id);member((UUID)row.get("organization_id"),a);db.update("UPDATE project.tasks SET title=COALESCE(?,title),description=COALESCE(?,description),status=COALESCE(?,status),priority=COALESCE(?,priority),assignee_id=COALESCE(?,assignee_id),due_date=COALESCE(?,due_date),updated_at=now() WHERE id=?",r.title(),r.description(),r.status(),r.priority(),r.assigneeId(),r.dueDate()==null?null:Date.valueOf(r.dueDate()),id);return db.queryForMap("SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE id=?",id);}
 private void member(UUID org,org.springframework.security.core.Authentication a){if(db.queryForObject("SELECT count(*) FROM org.memberships WHERE organization_id=? AND user_id=?",Integer.class,org,UUID.fromString(a.getName()))==0)throw new SecurityException("You do not have access to this workspace.");}
}
