package com.nexus.work;

import jakarta.validation.Valid; import jakarta.validation.constraints.NotBlank; import org.springframework.jdbc.core.JdbcTemplate; import org.springframework.web.bind.annotation.*; import java.sql.Date; import java.time.LocalDate; import java.util.*;

@RestController @RequestMapping("/api")
public class WorkController {
 private final JdbcTemplate db; public WorkController(JdbcTemplate db){this.db=db;}
 record CreateProject(@NotBlank String name,String description,UUID teamId){} record CreateTask(@NotBlank String title,String description,UUID teamId,UUID projectId,String priority,UUID assigneeId,LocalDate dueDate){} record UpdateTask(String title,String description,String status,String priority,UUID assigneeId,LocalDate dueDate){}
 @GetMapping("/orgs/{orgId}/projects") public List<Map<String,Object>> projects(@PathVariable UUID orgId,org.springframework.security.core.Authentication a){member(orgId,a);return db.queryForList("SELECT id,name,description,team_id FROM project.projects p WHERE organization_id=? AND deleted_at IS NULL AND (team_id IS NULL OR EXISTS (SELECT 1 FROM org.team_members tm WHERE tm.team_id=p.team_id AND tm.user_id=?)) ORDER BY updated_at DESC",orgId,UUID.fromString(a.getName()));}
 @PostMapping("/orgs/{orgId}/projects") public Map<String,Object> project(@PathVariable UUID orgId,@Valid @RequestBody CreateProject r,org.springframework.security.core.Authentication a){member(orgId,a);team(orgId,r.teamId(),a);UUID id=UUID.randomUUID();db.update("INSERT INTO project.projects(id,organization_id,team_id,name,description) VALUES(?,?,?,?,?)",id,orgId,r.teamId(),r.name().trim(),r.description());return Map.of("id",id,"name",r.name().trim(),"description",Objects.toString(r.description(),""),"teamId",r.teamId());}
 @GetMapping("/orgs/{orgId}/tasks") public List<Map<String,Object>> tasks(@PathVariable UUID orgId, @RequestParam(required=false) UUID teamId,org.springframework.security.core.Authentication a){member(orgId,a);if(teamId!=null)team(orgId,teamId,a);String q="SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE organization_id=? AND deleted_at IS NULL";return teamId==null?db.queryForList(q+" AND (team_id IS NULL OR EXISTS (SELECT 1 FROM org.team_members tm WHERE tm.team_id=project.tasks.team_id AND tm.user_id=?)) ORDER BY due_date NULLS LAST,updated_at DESC",orgId,UUID.fromString(a.getName())):db.queryForList(q+" AND team_id=? ORDER BY due_date NULLS LAST,updated_at DESC",orgId,teamId);}
 @PostMapping("/orgs/{orgId}/tasks") public Map<String,Object> task(@PathVariable UUID orgId,@Valid @RequestBody CreateTask r,org.springframework.security.core.Authentication a){member(orgId,a);team(orgId,r.teamId(),a);project(orgId,r.projectId());assignee(orgId,r.assigneeId());UUID id=UUID.randomUUID();db.update("INSERT INTO project.tasks(id,organization_id,project_id,team_id,title,description,priority,assignee_id,due_date) VALUES(?,?,?,?,?,?,?,?,?)",id,orgId,r.projectId(),r.teamId(),r.title().trim(),r.description(),Objects.toString(r.priority(),"MEDIUM"),r.assigneeId(),r.dueDate()==null?null:Date.valueOf(r.dueDate()));return db.queryForMap("SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE id=?",id);}
 @PatchMapping("/tasks/{id}") public Map<String,Object> update(@PathVariable UUID id,@RequestBody UpdateTask r,org.springframework.security.core.Authentication a){Map<String,Object> row=db.queryForMap("SELECT organization_id,team_id FROM project.tasks WHERE id=? AND deleted_at IS NULL",id);UUID org=(UUID)row.get("organization_id");member(org,a);team(org,(UUID)row.get("team_id"),a);assignee(org,r.assigneeId());db.update("UPDATE project.tasks SET title=COALESCE(?,title),description=COALESCE(?,description),status=COALESCE(?,status),priority=COALESCE(?,priority),assignee_id=COALESCE(?,assignee_id),due_date=COALESCE(?,due_date),updated_at=now() WHERE id=?",r.title(),r.description(),r.status(),r.priority(),r.assigneeId(),r.dueDate()==null?null:Date.valueOf(r.dueDate()),id);return db.queryForMap("SELECT id,title,description,status,priority,assignee_id,due_date,team_id,project_id FROM project.tasks WHERE id=?",id);}
 private void member(UUID org,org.springframework.security.core.Authentication a){if(db.queryForObject("SELECT count(*) FROM org.memberships WHERE organization_id=? AND user_id=?",Integer.class,org,UUID.fromString(a.getName()))==0)throw new SecurityException("You do not have access to this workspace.");}
 private void team(UUID org,UUID team,org.springframework.security.core.Authentication a){if(team==null)return;if(db.queryForObject("SELECT count(*) FROM org.teams t JOIN org.team_members tm ON tm.team_id=t.id WHERE t.id=? AND t.organization_id=? AND t.deleted_at IS NULL AND tm.user_id=?",Integer.class,team,org,UUID.fromString(a.getName()))==0)throw new SecurityException("You do not have access to this team.");}
 private void project(UUID org,UUID project){if(project!=null&&db.queryForObject("SELECT count(*) FROM project.projects WHERE id=? AND organization_id=? AND deleted_at IS NULL",Integer.class,project,org)==0)throw new IllegalArgumentException("Project does not belong to this workspace.");}
 private void assignee(UUID org,UUID assignee){if(assignee!=null&&db.queryForObject("SELECT count(*) FROM org.memberships WHERE organization_id=? AND user_id=?",Integer.class,org,assignee)==0)throw new IllegalArgumentException("Assignee is not a workspace member.");}
}
